### PR TITLE
Change the README to markdown

### PR DESCRIPTION
**Pull request by BenMorel**
This makes it more readable on GitHub, with minor changes to the file.

### CODE REVIEW

**Comment by strk** [comment]
I don't like the .md extension :)  -- but no problem with dropping a symlink with that name to the README (which is ok if renders correctly as markdown)

**Comment by BenMorel** [comment]
Then you can choose the alternative `.markdown` extension! :)

Joke aside, yes there are just minor modifications to make it render fine as markdown (such as 4 
spaces tabs instead of 2 spaces for code blocks).

I don't know if GitHub will render a symlink, though.

**Comment by strk** [comment]
I think it will, but I just remembered official code is in SVN
which I dubt supports symlinks.

Gah, I hate it to be forced to change file extension !

**Comment by BenMorel** [comment]
I don't want to force you, this is just a suggestion ... :)

**Comment by strk** [comment]
I took a different approach, adding another .md file just for the sake of github:
https://github.com/libgeos/libgeos/commit/aa57155d18f8cbb33b5090c5ea4bae349abf4db2

**Comment by BenMorel** [comment]
That's not so bad :)

**Pull request closed without merging**
