### PR TITLE
Add GEOSGeom_setPrecision function to C-API

### PR DESCRIPTION
**Pull request by strk**
Proposal for the ability to set the precision model for geometries
\cc @manisandro

### CODE REVIEW

**Comment by strk** [comment]
What I'm not convinced about in this proposal is that it is not flexible enough to expose a few configurations of the precision reducer, namely:

 - It enforces topology preservation in case of snapping
 - It enforces removal of collapsed elements

In the C++ API those two aspects are configurable.

A function with all configurations available could be:

 GEOSGeom_reduce(double gridsize, bool changepm, bool retaintopology, bool removecollapsed)

Then we'd miss the possibility to just change the PM w/out snapping, but that's many not really something we want to allow ?

**Comment by manisandro** [comment]
Personally I don't see a scenario where you want to change the precision model of a geometry without snapping, that would be rather confusing IMO.

**Comment by strk** [comment]
Alright, force-pushed a new version using flags. Supports all that GeometryPrecisionReducer supports. See how you like it. I'm writing a unit test now, with the crossing lines intersection...

**Comment by strk** [comment]
There might possibly be a case for snapping w/out changing the PrecisionModel though (but with this API it can be added w/out interface change)

**Comment by strk** [comment]
Committed to trunk: https://trac.osgeo.org/geos/changeset/4092

**Pull request closed without merging**
