### PR TITLE
Set/Get Geometry User Data in CAPI

### PR DESCRIPTION
**Pull request by gtourkas**
need to associate an numerical id with a set of geometry and build an SRTree to identify the geometries returned by GEOSSTRtree_nearest and GEOSSTRtree_query; Geometry's get/setUserData are appropriate for such a task but there are no wrappers in the CAPI

### CODE REVIEW

**Comment by strk** [comment]
If I'm not wrong the STRtree interface allows you to store
an opaque pointer as the value (while storing a Geometry as the key)
so you should be able to put your numerical ids into a larger
structure embedding a Geometry

**Comment by gtourkas** [comment]
@strk yes, one can use the GEOSSTRtree_nearest_generic but will also need to specify the distance function, which might be straightforward but also not so slick 

given that the geometry is providing a set/getUserData i thought a set of wrapper functions won't harm

**Comment by gtourkas** [comment]
@strk yes, one can use the GEOSSTRtree_nearest_generic but will also need to specify the distance function, which might be straightforward but also not so slick

given that the geometry is providing a set/getUserData i thought a set of wrapper functions won't harm

**Comment by strk** [comment]
Agree those functions won't harm.
Could you add a unit test for them under tests/unit/capi ?

**Comment by gtourkas** [comment]
tests committed

**Comment by strk** [comment]
Please:

1. Rename the methods to GEOSGeom_setUserData / GEOSGeom_getUserData
2. Enable the new testcase in the test/unit/Makefile.am (make sure "make check" runs the test)
3. Squash-rebase to trunk

**Comment by gtourkas** [comment]
@strk done

**Comment by strk** [comment]
tests/unit/Makefile.am still doesn't have an entry for
capi/GEOSUserDataTest.cpp

**Comment by gtourkas** [comment]
@strk it is - check the 5th section in the single push
screen shot 2016-09-06 at 10 44 29

**Comment by strk** [comment]
The function names are still not changed to be GEOSGeom_xxxx

**Comment by strk** [comment]
r4254 = 2b2645fd31cf881dbed0d2a1bc3f0013a57aa504 (refs/remotes/trunk)

**Pull request closed without merging**
